[package]
name = "test_wasm_weigh"
version = "0.0.1"
authors = [ "michael.dougherty@holo.host" ]
edition = "2021"

[lib]
name = "test_wasm_weigh"
crate-type = [ "cdylib", "rlib" ]

[[example]]
name = "integrity_test_wasm_weigh"
path = "src/integrity.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = "1.0"
hdk = { path = "../../../../hdk" }

[features]
default = []
mock = ["hdk/mock"]
